help:
	@echo "Targets available for triePatricia are: test"

CC=gcc
test: ../hashTable/dependencies/murmur3.c ../hashTable/hashTable.c ../linkedList/linkedList.c triePatricia.c triePatriciaTest.c 
	$(CC) -o triePTest ../hashTable/dependencies/murmur3.c ../hashTable/hashTable.c ../linkedList/linkedList.c triePatricia.c triePatriciaTest.c 

	 